////////////////////////////////
// List of available sequences by name and matching id
PSI_SEQ("Normal", NORMAL)
PSI_SEQ("Alarm", ALARM)
PSI_SEQ("Failure", FAILURE)
PSI_SEQ("Leia", LEIA)
PSI_SEQ("March", MARCH)
PSI_SEQ("Solid Color", SOLIDCOLOR)
PSI_SEQ("Flash Color", FLASHCOLOR)
PSI_SEQ("Flip Flop Color", FLIPFLOPCOLOR)
PSI_SEQ("Flip Flop Alt Color", FLIPFLOPALTCOLOR)
PSI_SEQ("Color Swap", COLORSWAP)
PSI_SEQ("Rainbow", RAINBOW)
PSI_SEQ("Red Alert", REDALERT)
PSI_SEQ("Mic Bright", MICBRIGHT)
PSI_SEQ("Mic Rainbow", MICRAINBOW)
PSI_SEQ("Lights Out", LIGHTSOUT)
PSI_SEQ("Roaming Pixel", ROAMINGPIXEL)
PSI_SEQ("Horizontal Scan", HORIZONTALSCANLINE)
PSI_SEQ("Vertical Scan", VERTICALSCANLINE)
PSI_SEQ("Fire", FIRE)
PSI_SEQ("Fire", FIRE)
PSI_SEQ("Color Wipe", PSICOLORWIPE)
PSI_SEQ("Pulse", PULSE)
PSI_SEQ("Random", RANDOM)
